context:
  project_id: "${env}-for-example"
  
  region_1: "asia-northeast3"
  zone_1: "asia-northeast3-a"

  #########################################
  ## network
  #########################################
  vpc_name_1: "dev-main"
  subnet_name_1: "dev-main-private"
  secondary_subnet_range_name_1: "asia-northeast3-k8s-pod-range"
  secondary_subnet_range_name_2: "asia-northeast3-k8s-service-range"




  #########################################
  ## ip 
  #########################################
  ip_key_1: "nonglobal-external-premium-ipv4-nat"
  ip_name_1: "dev-nat"




  #########################################
  ## nat 
  #########################################
  router_name_1: "dev-nat-router"
  nat_name_1: "dev-nat"




  #########################################
  ## gke 
  #########################################
  gke_name_1: "dev-primary"

  node_pool_name_1: "dev-primary-general"
  node_count_1: 3
  machine_type_1: "e2-medium"
  disk_size_gb_1: 20




  #########################################
  ## sa 
  #########################################
  sa_key_1: "for_ksa_workload_identity"
  key_1_sa_name_1: "dev-cluster"




  #########################################  
  ## sa_iam 
  #########################################
  sa_iam_key_1: "for_ksa_workload_identity"




  #########################################
  ## ar_iam 
  #########################################
  ar_iam_key_1: "for_pod_docker_image"




  #########################################
  ## sb_iam 
  #########################################




  #########################################
  ## database 
  #########################################




  #########################################
  ## registry
  #########################################
  repository_id_1: "dev-docker-registry"




  #########################################
  ## bucket 
  #########################################




  #########################################
  ## k8s_namespace
  #########################################
  k8s_namespace_name_1: "application"
  k8s_namespace_name_2: "argocd"




  #########################################
  ## k8s_sa
  #########################################




  #########################################
  ## helm
  #########################################
  helm_name_1: "argocd"




  #########################################
  ## kubectl
  #########################################




  #########################################
  ## vm
  #########################################