apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: <Project Name>
  namespace: argocd
spec:
  description: "<Project Description>"
  sourceRepos:
    - '<Github Manifest Repository HTTPS Address>'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
